apiVersion: v1
kind: Pod
metadata: 
  name: pod-pv
spec: 
  containers: 
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      # hostPath: 
      #   path: /home/hugo_/kubernetes-volume
      #   type: Directory
      persistentVolumeClaim: 
        claimName: pvc-1