apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
  labels: 
    app: segundo-pod
    chave: valor
    qualquer: coisa
spec: 
  containers: 
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80