apiVersion: v1
kind: Pod
metadata: 
  name: portal-noticias
  labels:
    app: portal-noticias
spec: 
  containers: 
    - name: portal-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 8080
      envFrom: 
        - configMapRef:
            name: portal-configmap