---
######## DOCKER INSTALL ######## 
- name: 'Adiciona packages' 
  yum: 
    name: 'yum-utils'
    state: latest
  become: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: 'Instala o Docker e suas dependencias' 
  yum: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
  become: yes

- name: 'Inicia o serviço Docker'
  service: 
    name: docker
    state: started
  become: yes

